// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'news_app';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String BUSINESS = 'assets/BUSINESS.jpg';
  static const String ENTERTAINMENT = 'assets/ENTERTAINMENT.jpg';
  static const String GENERALS = 'assets/GENERALS.jpg';
  static const String HEALTH = 'assets/HEALTH.jpg';
  static const String SCIENCE = 'assets/SCIENCE.jpg';
  static const String SPORTS = 'assets/SPORTS.jpg';
  static const String TECHNOLOGY = 'assets/TECHNOLOGY.jpg';
  static const String DOWNLOAD = 'assets/download.jpg';
  static const String OLX = 'assets/olx.jpg';
  static const String VIG = 'assets/vig.jpg';
}
